In [ ]:
from google.colab import drive; drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import os
os.chdir("/content/drive/My Drive/Colab Notebooks")
os.getcwd()

'/content/drive/My Drive/Colab Notebooks'

In [ ]:
import tensorflow as tf
print(tf.__version__)
import numpy as np


2.2.0


In [ ]:
!python prepare_data2.py -m 500 -p the-king-james-bible.txt kjb [0-9]+:[0-9]+ 

2020-06-04 16:48:51.760603: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Split input into 31103 sequences...
Longest sequence is 533 characters. If this seems unreasonable, consider using the maxlen argument!
Removing sequences longer than 500 characters...
31102 sequences remaining.
Longest remaining sequence has length 448.
Removing length-0 sequences...
31102 sequences remaining.
Serialized 100 sequences...
Serialized 200 sequences...
Serialized 300 sequences...
Serialized 400 sequences...
Serialized 500 sequences...
Serialized 600 sequences...
Serialized 700 sequences...
Serialized 800 sequences...
Serialized 900 sequences...
Serialized 1000 sequences...
Serialized 1100 sequences...
Serialized 1200 sequences...
Serialized 1300 sequences...
Serialized 1400 sequences...
Serialized 1500 sequences...
Serialized 1600 sequences...
Serialized 1700 sequences...
Serialized 1800 sequences...
Serialized 1900 sequences...

In [ ]:
!python prepare_data2.py -m 200 shakespeare_input.txt skp \\n\\n+ 

2020-06-04 16:49:04.411996: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Split input into 31022 sequences...
Longest sequence is 3094 characters. If this seems unreasonable, consider using the maxlen argument!
Removing sequences longer than 200 characters...
24842 sequences remaining.
Longest remaining sequence has length 199.
Removing length-0 sequences...
24842 sequences remaining.
Serialized 100 sequences...
Serialized 200 sequences...
Serialized 300 sequences...
Serialized 400 sequences...
Serialized 500 sequences...
Serialized 600 sequences...
Serialized 700 sequences...
Serialized 800 sequences...
Serialized 900 sequences...
Serialized 1000 sequences...
Serialized 1100 sequences...
Serialized 1200 sequences...
Serialized 1300 sequences...
Serialized 1400 sequences...
Serialized 1500 sequences...
Serialized 1600 sequences...
Serialized 1700 sequences...
Serialized 1800 sequences...
Serialized 1900 sequences..

### *Variable Length Sequences using Masking*

In [ ]:
import pickle

import tensorflow as tf
from prepare_data2 import parse_seq


# data
bs = 128
seq_len = 200
data = tf.data.TFRecordDataset("skp.tfrecords")
# data = tf.data.Dataset.
data = data.map(lambda x: parse_seq(x))
data = data.padded_batch(bs+1,padded_shapes=seq_len,drop_remainder=True)
vocab = pickle.load(open("skp_vocab", mode="rb"))
vocab_size = len(vocab)
ind_to_ch = {ind: ch for (ch, ind) in vocab.items()}

print(ind_to_ch)
print(vocab_size)
print(data)

{3: 'Y', 4: 'P', 5: 'w', 6: 'O', 7: 'k', 8: '?', 9: 'y', 10: 'o', 11: 'g', 12: 'p', 13: ';', 14: 'E', 15: 'J', 16: 'C', 17: 'T', 18: 'x', 19: 'Q', 20: 'e', 21: '&', 22: 'U', 23: 'H', 24: 'K', 25: 'n', 26: 'u', 27: 'I', 28: 'j', 29: 's', 30: 'z', 31: 'a', 32: 'A', 33: 'Z', 34: 'D', 35: 'h', 36: 'b', 37: 'B', 38: 'q', 39: 'm', 40: 'l', 41: 'f', 42: 'G', 43: 't', 44: 'v', 45: '$', 46: '\n', 47: "'", 48: 'i', 49: '[', 50: 'M', 51: 'F', 52: '!', 53: 'R', 54: ']', 55: ' ', 56: 'V', 57: '3', 58: 'c', 59: 'r', 60: 'S', 61: 'W', 62: 'L', 63: '-', 64: ',', 65: 'N', 66: 'X', 67: '.', 68: ':', 69: 'd', 0: '<PAD>', 1: '<S>', 2: '</S>'}
70
<PaddedBatchDataset shapes: (129, 200), types: tf.int32>


In [ ]:
for ind, thing in enumerate(data): 
    print(tf.shape(thing))
    print(thing)
    print(tf.shape(thing[0]))
    inds = thing[0].numpy()
    print(inds)
    to_chars = "".join([ind_to_ch[ind] for ind in inds])
    #print(ind)
    print(to_chars)
    #print()
    break

tf.Tensor([129 200], shape=(2,), dtype=int32)
tf.Tensor(
[[ 1 51 48 ...  0  0  0]
 [ 1 32 40 ...  0  0  0]
 [ 1 51 48 ...  0  0  0]
 ...
 [ 1 51 48 ...  0  0  0]
 [ 1 60 20 ...  0  0  0]
 [ 1 51 48 ...  0  0  0]], shape=(129, 200), dtype=int32)
tf.Tensor([200], shape=(1,), dtype=int32)
[ 1 51 48 59 29 43 55 16 48 43 48 30 20 25 68 46 37 20 41 10 59 20 55  5
 20 55 12 59 10 58 20 20 69 55 31 25  9 55 41 26 59 43 35 20 59 64 55 35
 20 31 59 55 39 20 55 29 12 20 31  7 67  2  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0]
<S>First Citizen:
Before we proceed any further, hear me speak.</S><PAD><PAD><PAD><PAD><PAD><PAD><PAD><

In [ ]:
def split_input_target(chunk):
    input_text = chunk[:-1]
    target_text = chunk[1:]
    return input_text, target_text

dataset = data.map(split_input_target)
print(dataset)

<MapDataset shapes: ((128, 200), (128, 200)), types: (tf.int32, tf.int32)>


In [ ]:
for input_example, target_example in  dataset.take(1):
  print ('Input data: ', repr(''.join(ind_to_ch[i] for i in input_example.numpy().flatten())))
  print ('Target data:', repr(''.join(ind_to_ch[i] for i in target_example.numpy().flatten())))

Input data:  "<S>First Citizen:\nBefore we proceed any further, hear me speak.</S><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><S>All:\nSpeak, speak.</S><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><P

In [ ]:
from tensorflow.keras import layers
def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
  model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim,
                              batch_input_shape=[batch_size, None]),
    tf.keras.layers.LSTM(rnn_units,
                        return_sequences=True,
                        stateful=True,
                        recurrent_initializer='glorot_uniform'),
    tf.keras.layers.Dense(vocab_size)
  ])
  return model


In [ ]:
model = build_model(
  vocab_size = vocab_size,
  embedding_dim=256,
  rnn_units=512,
  batch_size=bs)
model.summary()
opt = tf.optimizers.Adam()
batch_loss = tf.constant(0.)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (128, None, 256)          17920     
_________________________________________________________________
lstm (LSTM)                  (128, None, 512)          1574912   
_________________________________________________________________
dense (Dense)                (128, None, 70)           35910     
Total params: 1,628,742
Trainable params: 1,628,742
Non-trainable params: 0
_________________________________________________________________


In [ ]:
for epoch in range(50):
 for input_example_batch, target_example_batch in dataset:
  loss = tf.constant(0.)
  batch_loss = tf.constant(0.) 
  with tf.GradientTape() as tape:
    example_batch_predictions = model(input_example_batch,training=True)
    loss = tf.nn.sparse_softmax_cross_entropy_with_logits(target_example_batch,example_batch_predictions)
    non_zero = tf.TensorArray(tf.int64,size=bs)
    for seq in tf.range(bs):
      count = tf.math.count_nonzero(input_example_batch[seq])-1
      non_zero.write(seq,count).mark_used()
    non_zero=non_zero.stack()
    mask = tf.sequence_mask(non_zero,maxlen=seq_len,dtype=tf.float32)
    loss = tf.math.multiply(mask,loss)
    loss = tf.reduce_sum(loss,axis=1)
    loss = loss/tf.cast(non_zero,tf.float32)
    batch_loss = tf.reduce_mean(loss)
  varis = model.trainable_variables
  grads = tape.gradient(batch_loss,varis)
  glob_norm = tf.linalg.global_norm(grads)
  grads = [g/glob_norm for g in grads]
  opt.apply_gradients(zip(grads,varis))
  model.save_weights('weights')
  model.reset_states()
 print("Epoch  {} ,Loss : {}".format(epoch,batch_loss))

Epoch  0 ,Loss : 2.7859854698181152
Epoch  1 ,Loss : 2.7555055618286133
Epoch  2 ,Loss : 2.742432117462158
Epoch  3 ,Loss : 2.7288780212402344
Epoch  4 ,Loss : 2.723067283630371
Epoch  5 ,Loss : 2.7179675102233887
Epoch  6 ,Loss : 2.7143115997314453
Epoch  7 ,Loss : 2.7105302810668945
Epoch  8 ,Loss : 2.7064805030822754
Epoch  9 ,Loss : 2.7022008895874023
Epoch  10 ,Loss : 2.699367046356201
Epoch  11 ,Loss : 2.695673942565918
Epoch  12 ,Loss : 2.679187297821045
Epoch  13 ,Loss : 2.662787914276123
Epoch  14 ,Loss : 2.6639745235443115
Epoch  15 ,Loss : 2.6699929237365723
Epoch  16 ,Loss : 2.647353172302246
Epoch  17 ,Loss : 2.6397125720977783
Epoch  18 ,Loss : 2.621159791946411
Epoch  19 ,Loss : 2.6089088916778564
Epoch  20 ,Loss : 2.6017160415649414
Epoch  21 ,Loss : 2.581871747970581
Epoch  22 ,Loss : 2.5784413814544678
Epoch  23 ,Loss : 2.563582420349121
Epoch  24 ,Loss : 2.559443235397339
Epoch  25 ,Loss : 2.527071952819824
Epoch  26 ,Loss : 2.4870669841766357
Epoch  27 ,Loss : 2.463

## *Sampling with Keras*

In [ ]:
gen_model = build_model(
  vocab_size = vocab_size,
  embedding_dim=256,
  rnn_units=512,
  batch_size=1)
gen_model.summary()
opt = tf.optimizers.Adam()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (1, None, 256)            17920     
_________________________________________________________________
lstm_1 (LSTM)                (1, None, 512)            1574912   
_________________________________________________________________
dense_1 (Dense)              (1, None, 70)             35910     
Total params: 1,628,742
Trainable params: 1,628,742
Non-trainable params: 0
_________________________________________________________________


In [ ]:
gen_model.load_weights('weights')
# print(gen_model.trainable_variables)

In [ ]:
char2idx = {u:i for i, u in enumerate(vocab)}
# print(char2idx)
def generate_text(model, start_string):
  # Evaluation step (generating text using the learned model)

  # Number of characters to generate
  num_generate = 1000

  # Converting our start string to numbers (vectorizing)
  input_eval = [0]#[char2idx[s] for s in start_string]
  input_eval = tf.expand_dims(input_eval, 0)



  # Empty string to store our results
  text_generated = []

  # Low temperatures results in more predictable text.
  # Higher temperatures results in more surprising text.
  # Experiment to find the best setting.
  temperature = 1.0

  # Here batch size == 1
  model.reset_states()
  for i in range(num_generate):
      # print(tf.shape(input_eval))
      predictions = model(input_eval)
      # remove the batch dimension
      predictions = tf.squeeze(predictions, 0)

      # using a categorical distribution to predict the character returned by the model
      predictions = predictions / temperature
      predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

      # We pass the predicted character as the next input to the model
      # along with the previous hidden state
      input_eval = tf.expand_dims([predicted_id], 0)

      if(ind_to_ch[predicted_id]!= '<\S>'):
        text_generated.append(ind_to_ch[predicted_id])

  return (start_string + ''.join(text_generated))

In [ ]:
print(generate_text(gen_model, "JULIET: "))

JULIET: &&JNf,,&akBQnggLLooQOOsOQ<PAD>oL<PAD>!<PAD><PAD><PAD><PAD><PAD><PAD>l<PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD>!<PAD>e<PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD>R<PAD><PAD><PAD><PAD>IP<PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD>I<PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD>A<PAD><PAD><PAD><PAD><PAD><PAD>l<PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD>S<PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD>!<PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD>O<PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD>H<PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><

In [ ]:
§import numpy as np

def sample(steps):
    init_state = tf.Variable(tf.initializers.glorot_uniform()([bs, seq_len]))
    gen = [0]

    for step in range(100):
        state = gen_model(init_state)
        probs = tf.nn.softmax(state).numpy
        print(tf.shape(probs))
        # #gen.append(np.argmax(probs))  # use argmax instead of choice if you want
        gen.append(np.random.choice(vocab_size, p=probs.flatten()))
    return "".join([ind_to_ch[ind] for ind in gen])
        
agg = sample(2000)

## *Reimplementation of low_level_rnn using Keras*

In [ ]:
!python prepare_data.py shakespeare_input.txt skp1

In [ ]:
from prepare_data import parse_seq
# this is just a datasets of "bytes" (not understandable)
data = tf.data.TFRecordDataset("skp1.tfrecords")

# this maps a parser function that properly interprets the bytes over the dataset
# (with fixed sequence length 200)
# if you change the sequence length in preprocessing you also need to change it here
data = data.map(lambda x: parse_seq(x, 200))
# data = data.map(lambda x: parse_seq(x))

# a map from characters to indices
vocab = pickle.load(open("skp1_vocab", mode="rb"))
vocab_size = len(vocab)
# inverse mapping: indices to characters
ind_to_ch = {ind: ch for (ch, ind) in vocab.items()}

print(vocab)
print(vocab_size)

{'?': 1, 'E': 2, 'O': 3, 'p': 4, 'V': 5, ' ': 6, 'o': 7, 'R': 8, '\n': 9, 'a': 10, 'g': 11, 'c': 12, 't': 13, 'i': 14, 'u': 15, 'k': 16, 'Y': 17, '.': 18, 'U': 19, 'n': 20, 'f': 21, 'S': 22, 'G': 23, '&': 24, 'Z': 25, 'M': 26, 'A': 27, 'r': 28, 'z': 29, 'l': 30, 'L': 31, 'X': 32, '!': 33, 'd': 34, 'j': 35, 'y': 36, 'v': 37, 'x': 38, '$': 39, '3': 40, ']': 41, 'W': 42, 'D': 43, 'h': 44, 'e': 45, 'P': 46, 'w': 47, "'": 48, ':': 49, 'B': 50, ';': 51, ',': 52, '-': 53, 'J': 54, '[': 55, 'N': 56, 'H': 57, 'F': 58, 'b': 59, 'm': 60, 'T': 61, 'q': 62, 'C': 63, 'Q': 64, 's': 65, 'K': 66, 'I': 67, '<S>': 0}
68


In [ ]:
def split_input_target(chunk):
    input_text = chunk[:-1]
    target_text = chunk[1:]
    return input_text, target_text

dataset = data.map(split_input_target)
dataset

<MapDataset shapes: ((199,), (199,)), types: (tf.int32, tf.int32)>

In [ ]:
dataset = dataset.shuffle(22981).batch(128, drop_remainder= True)
embedding_dim = 512
rnn_units = 1024
batch_size = 128

In [ ]:
def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
  model = tf.keras.Sequential(name= 'GRU')
  model.add(tf.keras.layers.Embedding(vocab_size, embedding_dim, batch_input_shape=[batch_size, None]))
  model.add(tf.keras.layers.GRU(rnn_units, return_sequences= True, stateful= True, recurrent_initializer= 'glorot_uniform'))
  model.add(tf.keras.layers.Dense(vocab_size))
  return model


model = build_model(vocab_size, embedding_dim, rnn_units, batch_size)
model.summary()

Model: "GRU"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (128, None, 512)          34816     
_________________________________________________________________
gru (GRU)                    (128, None, 1024)         4724736   
_________________________________________________________________
dense_3 (Dense)              (128, None, 68)           69700     
Total params: 4,829,252
Trainable params: 4,829,252
Non-trainable params: 0
_________________________________________________________________


In [ ]:
for input_example_batch, target_example_batch in dataset.take(1):
  example_batch_predictions = model(input_example_batch)
  print(example_batch_predictions.shape, "# (batch_size, sequence_length, vocab_size)")

sampled_ind = tf.random.categorical(example_batch_predictions[0], num_samples= 1)
sampled_ind = tf.squeeze(sampled_ind, axis= -1).numpy()

# sampled_ind
input_example_batch1 = input_example_batch[0].numpy()
# input_example_batch1
print("Input: \n", repr("".join([ind_to_ch[ind] for ind in input_example_batch1])))
print()
print("Next Char Predictions: \n", repr("".join([ind_to_ch[ind] for ind in sampled_ind])))

(128, 199, 68) # (batch_size, sequence_length, vocab_size)
Input: 
 "<S>kilful pilot's charge?\nWe will not from the helm to sit and weep,\nBut keep our course, though the rough wind say no,\nFrom shelves and rocks that threaten us with wreck.\nAs good to chide the waves as"

Next Char Predictions: 
 "cKPoLr]Uo3bmntmnhcWnZjXflVb\nVyf$M ?JegsSxo'W]A,lKX$kOt, WfXl',:EwAqMD!ZLel3v-AG; yXyS?eOS'Biwl,MDFd IeWqmpL<S>RG3mIDDMVkV o!JAsh$nM 'nW$alJkd-mAQISobi]Bgi[BT\nZZzvtKE'OZS-F']Xhtj\n$NJW$\ncXTidUWTUvFrAOHxX"


In [ ]:
def loss(labels, logits):
  return tf.keras.losses.sparse_categorical_crossentropy(labels, logits, from_logits= True)


example_batch_loss = loss(target_example_batch, example_batch_predictions)
print("Mean Loss: ", example_batch_loss.numpy().mean())

Mean Loss:  4.21916


In [ ]:
model.compile(optimizer= 'Adam', loss= loss)

# Directory where the checkpoints will be saved
checkpoint_dir = './training_checkpoints'
# Name of the checkpoint files
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True)

history = model.fit(dataset, epochs= 10, callbacks=[checkpoint_callback])

Epoch 1/10
179/179 [==============================] - 81s 454ms/step - loss: 2.5174
Epoch 2/10
179/179 [==============================] - 82s 460ms/step - loss: 1.7971
Epoch 3/10
179/179 [==============================] - 82s 461ms/step - loss: 1.5450
Epoch 4/10
179/179 [==============================] - 82s 461ms/step - loss: 1.4246
Epoch 5/10
179/179 [==============================] - 83s 462ms/step - loss: 1.3585
Epoch 6/10
179/179 [==============================] - 83s 461ms/step - loss: 1.3155
Epoch 7/10
179/179 [==============================] - 83s 462ms/step - loss: 1.2839
Epoch 8/10
179/179 [==============================] - 83s 461ms/step - loss: 1.2579
Epoch 9/10
179/179 [==============================] - 83s 462ms/step - loss: 1.2356
Epoch 10/10
179/179 [==============================] - 83s 462ms/step - loss: 1.2160


In [ ]:
model = build_model(vocab_size, embedding_dim, rnn_units, batch_size= 1)
model.load_weights(tf.train.latest_checkpoint(checkpoint_dir))
model.build(tf.TensorShape([1, None]))
model.summary()

Model: "GRU"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (1, None, 512)            34816     
_________________________________________________________________
gru_1 (GRU)                  (1, None, 1024)           4724736   
_________________________________________________________________
dense_4 (Dense)              (1, None, 68)             69700     
Total params: 4,829,252
Trainable params: 4,829,252
Non-trainable params: 0
_________________________________________________________________


In [ ]:
char2idx = {u:i for i, u in enumerate(vocab)}

def generate_text(model, start_string):
  # Evaluation step (generating text using the learned model)

  # Number of characters to generate
  num_generate = 1000

  # Converting our start string to numbers (vectorizing)
  input_eval = [char2idx[s] for s in start_string]
  input_eval = tf.expand_dims(input_eval, 0)

  # Empty string to store our results
  text_generated = []

  # Low temperatures results in more predictable text.
  # Higher temperatures results in more surprising text.
  # Experiment to find the best setting.
  temperature = 1.0

  # Here batch size == 1
  model.reset_states()
  for i in range(num_generate):
      predictions = model(input_eval)
      # remove the batch dimension
      predictions = tf.squeeze(predictions, 0)

      # using a categorical distribution to predict the character returned by the model
      predictions = predictions / temperature
      predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

      # We pass the predicted character as the next input to the model
      # along with the previous hidden state
      input_eval = tf.expand_dims([predicted_id], 0)

      # text_generated.append(idx2char[predicted_id])
      text_generated.append(ind_to_ch[predicted_id])

  return (start_string + ''.join(text_generated))

In [ ]:
print(generate_text(model, "JULIET: "))

JULIET: :
Us known the worsting Romans?

MACDUFF:
Your daughter comes to be here.

MARIANA:
I am servant, thou hadst.
What a gods take in't in living thea?

THAISA:
With a creature disgrabell'd with you.

ANTIPHOLUS OF SYRACUSE:
O, there was little, and that legs banish'd,
Homeans done to see an elemies still,
Or so by 't. I thank you, trust not my mind.

CORIOLANUS:
Ah, that would that?

LOWELLUS:
Well, my gentlemen, fat inhabitable
For graw I am nobly side.

Geose,
Where are low and sky; and I cannot tell my indeed?

CLOTEN:
Ciect, sovereign; and the gentleman rightful
a heart-grace to come.

PAROLLES:
Is the fumies of the fatal spites?

SIMPROCUS:
How is't that was his cource, vexation now
have but to hasten thee, by the sharping of it;
Leave me: I will abuse. Playfold, for I am,
so fall off his sullen person, touchet; there
In second title to the high purses, heart--
Thou hast prevate thy brain together!
I protest, I stand by wat
Which Dealines to his majesty is it
true, the boasty